version: "3"
services:
  devcontainer_desktop_app_sample:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - ..:/project
    image: devcontainer_desktop_app_sample-image
    container_name: devcontainer_desktop_app_sample-container
    tty: true
